# local に develop(開発ブランチ) をデプロイする
# 環境は develop branch は next デプロイ先は実行フォルダ内の dev
localhost('local-dev')
  ->stage('develop')
  ->set('branch', 'next')
  ->set('deploy_path', get('current_dir').'/dev');

# local に 本番(prod) をデプロイする
# 環境は develop branch は next デプロイ先は実行フォルダ内の dev
localhost('local-dev')
  ->stage('develop')
  ->set('branch', 'next')
  ->set('deploy_path', get('current_dir').'/pro');
